<a href="https://colab.research.google.com/github/AadityaAdh/String_tensors/blob/main/String_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

yo vanya chai tensor vitra numeric value na hali kana string haru chai halni



In [ ]:
tf.constant(["hello","i am  ","human"])
#note string ko aagadi b aauxa

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'hello', b'i am  ', b'human'], dtype=object)>

yedi kunai numeric values vako tensor haru xa aaba teslai string tensor ma convert garnu paryo vanae

tf.strings.as_string(your tensor)



In [ ]:
t=tf.constant([1,2,3,4])
t

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.strings.as_string(t)

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'1', b'2', b'3', b'4'], dtype=object)>

#yedi join garna man lage tf.strings.join


Perform element-wise concatenation of a list of string tensors.

Given a list of string tensors of same shape, performs element-wise concatenation of the strings of the same index in all tensors.

In [ ]:
tf.strings.join(['abc','def']).numpy()




b'abcdef'

In [ ]:
tf.strings.join([['abc','123'],
                 ['def','456'],
                 ['ghi','789']]).numpy()



array([b'abcdefghi', b'123456789'], dtype=object)

In [ ]:
tf.strings.join([['abc','123'],
                 ['def','456']],
                 separator=" b").numpy()
#seperator vanya join garda duita element ko bich ma k rakhni

array([b'abc bdef', b'123 b456'], dtype=object)

In [ ]:
a=tf.constant(["hello","hi","namaskar","namaste"],shape=[2,1,2])
a

<tf.Tensor: shape=(2, 1, 2), dtype=string, numpy=
array([[[b'hello', b'hi']],

       [[b'namaskar', b'namaste']]], dtype=object)>

In [ ]:
tf.strings.join(a)

<tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'hellonamaskar', b'hinamaste']], dtype=object)>

In [ ]:
#jati dimension vayae ni matrix vitra xire ra index same(column ko index vanya) vako jodxa

#note;yeutai matrix vitra jodi raa xa